### try..catch程序的输出结果

```js
(function () {
  try {
      throw new Error();
  } catch (x) {
      var x = 1, y = 2;
      console.log(x);
  }
  console.log(x);
  console.log(y);
})();
```
<details>
  <summary>参考答案</summary>

  ```js
  //输出结果
  1
  undefined
  2

  //分析
  (function () {
    var x,y;  // 外部变量提升
    try {
        throw new Error();
    } catch (x/* 内部的x */) {
    x = 1; //内部的x，和上面声明的x不是一回事！！
          y = 2; //内部没有声明，作用域链向上找，外面的y
        console.log(x); //当然是1
    }
    console.log(x);  //只声明，未赋值，undefined
    console.log(y);  //就是2了
  })();
  ```

</details>
